const users = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson1@example.com",
    password: "password123",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith2@example.com",
    password: "qwerty456",
  },
  {
    id: 3,
    name: "Charlie Davis",
    email: "charlie.davis3@example.com",
    password: "letmein789",
  },
  {
    id: 4,
    name: "Diana Roberts",
    email: "diana.roberts4@example.com",
    password: "secret321",
  },
  {
    id: 5,
    name: "Ethan Clark",
    email: "ethan.clark5@example.com",
    password: "pass1234",
  },
  {
    id: 6,
    name: "Fiona Lewis",
    email: "fiona.lewis6@example.com",
    password: "ilovecats",
  },
  {
    id: 7,
    name: "George Hall",
    email: "george.hall7@example.com",
    password: "12345678",
  },
  {
    id: 8,
    name: "Hannah Allen",
    email: "hannah.allen8@example.com",
    password: "hunter2",
  },
  {
    id: 9,
    name: "Ian Young",
    email: "ian.young9@example.com",
    password: "sunshine",
  },
  {
    id: 10,
    name: "Julia Hernandez",
    email: "julia.hernandez10@example.com",
    password: "football1",
  },
  {
    id: 11,
    name: "Kevin King",
    email: "kevin.king11@example.com",
    password: "monkeyman",
  },
  {
    id: 12,
    name: "Laura Wright",
    email: "laura.wright12@example.com",
    password: "hello123",
  },
  {
    id: 13,
    name: "Michael Scott",
    email: "michael.scott13@example.com",
    password: "dundermifflin",
  },
  {
    id: 14,
    name: "Nina Adams",
    email: "nina.adams14@example.com",
    password: "changeme",
  },
  {
    id: 15,
    name: "Oscar Evans",
    email: "oscar.evans15@example.com",
    password: "supersecure",
  },
  {
    id: 16,
    name: "Paula Morris",
    email: "paula.morris16@example.com",
    password: "mypassword",
  },
  {
    id: 17,
    name: "Quentin Price",
    email: "quentin.price17@example.com",
    password: "testpass1",
  },
  {
    id: 18,
    name: "Rachel Cox",
    email: "rachel.cox18@example.com",
    password: "blueberry",
  },
  {
    id: 19,
    name: "Steve Diaz",
    email: "steve.diaz19@example.com",
    password: "redapple",
  },
  {
    id: 20,
    name: "Tina Rogers",
    email: "tina.rogers20@example.com",
    password: "greendog",
  },
  {
    id: 21,
    name: "Uma Bell",
    email: "uma.bell21@example.com",
    password: "purplecar",
  },
  {
    id: 22,
    name: "Victor Cooper",
    email: "victor.cooper22@example.com",
    password: "dragonfly",
  },
  {
    id: 23,
    name: "Wendy Reed",
    email: "wendy.reed23@example.com",
    password: "cheesecake",
  },
  {
    id: 24,
    name: "Xander Bailey",
    email: "xander.bailey24@example.com",
    password: "robot42",
  },
  {
    id: 25,
    name: "Yara Patterson",
    email: "yara.patterson25@example.com",
    password: "pass4321",
  },
  {
    id: 26,
    name: "Zack Torres",
    email: "zack.torres26@example.com",
    password: "nomoresecrets",
  },
  {
    id: 27,
    name: "Amy Fisher",
    email: "amy.fisher27@example.com",
    password: "blueocean",
  },
  {
    id: 28,
    name: "Ben Freeman",
    email: "ben.freeman28@example.com",
    password: "mountain1",
  },
  {
    id: 29,
    name: "Cindy Ellis",
    email: "cindy.ellis29@example.com",
    password: "skyhigh",
  },
  {
    id: 30,
    name: "Derek Stone",
    email: "derek.stone30@example.com",
    password: "riverbank",
  },
  {
    id: 31,
    name: "Ella Griffin",
    email: "ella.griffin31@example.com",
    password: "tinybird",
  },
  {
    id: 32,
    name: "Frankie Hunt",
    email: "frankie.hunt32@example.com",
    password: "hiddenleaf",
  },
  {
    id: 33,
    name: "Grace Wells",
    email: "grace.wells33@example.com",
    password: "tokyo123",
  },
  {
    id: 34,
    name: "Henry Ford",
    email: "henry.ford34@example.com",
    password: "carengine",
  },
  {
    id: 35,
    name: "Isla Bishop",
    email: "isla.bishop35@example.com",
    password: "sunnyday",
  },
  {
    id: 36,
    name: "Jake Richards",
    email: "jake.richards36@example.com",
    password: "crimsonsky",
  },
  {
    id: 37,
    name: "Kara Arnold",
    email: "kara.arnold37@example.com",
    password: "goldfish",
  },
  {
    id: 38,
    name: "Leo Chapman",
    email: "leo.chapman38@example.com",
    password: "graywolf",
  },
  {
    id: 39,
    name: "Maya Lane",
    email: "maya.lane39@example.com",
    password: "cloud99",
  },
  {
    id: 40,
    name: "Noah Ellis",
    email: "noah.ellis40@example.com",
    password: "deepsea",
  },
  {
    id: 41,
    name: "Olivia Turner",
    email: "olivia.turner41@example.com",
    password: "thunder1",
  },
  {
    id: 42,
    name: "Peter Hayes",
    email: "peter.hayes42@example.com",
    password: "ironman",
  },
  {
    id: 43,
    name: "Queenie Palmer",
    email: "queenie.palmer43@example.com",
    password: "strongwind",
  },
  {
    id: 44,
    name: "Ricky Blair",
    email: "ricky.blair44@example.com",
    password: "gladiator",
  },
  {
    id: 45,
    name: "Sophie Newton",
    email: "sophie.newton45@example.com",
    password: "infinity",
  },
  {
    id: 46,
    name: "Tommy May",
    email: "tommy.may46@example.com",
    password: "nintendo",
  },
  {
    id: 47,
    name: "Ursula Watts",
    email: "ursula.watts47@example.com",
    password: "rainstorm",
  },
  {
    id: 48,
    name: "Violet Nash",
    email: "violet.nash48@example.com",
    password: "grapevine",
  },
  {
    id: 49,
    name: "Walter Gibbs",
    email: "walter.gibbs49@example.com",
    password: "megabyte",
  },
  {
    id: 50,
    name: "Xenia Marsh",
    email: "xenia.marsh50@example.com",
    password: "silverkey",
  },
  // Continue to 100 if needed
];

module.exports = users;
